import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'todo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className="mx-w-3xl mx-auto p-4">
       <Header />
       <div className="mt-8">{children}</div>
       </div>
      </body>
    </html>
  )
}
